export const mockEateries = [
  {
    id: 1,
    name: "Tian Tian Chicken Rice",
    cuisine: "Chinese",
    neighborhood: "Maxwell",
    rating: 4.8,
    reviewCount: 3205,
    price: "$",
    imageUrl: "https://i.imgur.com/e3vsl5S.jpeg",
  },
  {
    id: 6,
    name: "Tiong Bahru Bakery",
    cuisine: "Cafe",
    neighborhood: "Tiong Bahru",
    rating: 4.7,
    reviewCount: 4100,
    price: "$$",
    imageUrl: "https://i.imgur.com/9v4J4T3.jpeg",
  },
  {
    id: 3,
    name: "Hill Street Tai Hwa Pork Noodle",
    cuisine: "Noodles",
    neighborhood: "Crawford Lane",
    rating: 4.6,
    reviewCount: 1800,
    price: "$$",
    imageUrl: "https://i.imgur.com/L3g2AAL.jpeg",
  },
  {
    id: 4,
    name: "328 Katong Laksa",
    cuisine: "Peranakan",
    neighborhood: "Katong",
    rating: 4.5,
    reviewCount: 2100,
    price: "$",
    imageUrl: "https://i.imgur.com/i97eFk2.jpeg",
  },
  {
    id: 5,
    name: "Nylon Coffee Roasters",
    cuisine: "Cafe",
    neighborhood: "Everton Park",
    rating: 4.9,
    reviewCount: 950,
    price: "$$",
    imageUrl: "https://i.imgur.com/gAOcjSj.jpeg",
  },
  {
    id: 7,
    name: "Apartment Coffee",
    cuisine: "Cafe",
    neighborhood: "Lavender",
    rating: 4.8,
    reviewCount: 880,
    price: "$$",
    imageUrl: "https://i.imgur.com/P4qgYVl.jpeg",
  },
  {
    id: 8,
    name: "The Ritual",
    cuisine: "Western",
    neighborhood: "Bukit Timah",
    rating: 4.6,
    reviewCount: 500,
    price: "$$$",
    imageUrl: "https://i.imgur.com/4gS1Z5S.jpeg",
  },
];